-- This file is autogenerated from regen-schema.ts
create table if not exists
  predictle_daily (
    created_time timestamp with time zone default now(),
    data jsonb not null,
    date_pt text primary key not null
  );

-- Row Level Security
alter table predictle_daily enable row level security;

-- Policies
drop policy if exists "public read" on predictle_daily;

create policy "public read" on predictle_daily for
select
  using (true);

-- Indexes
drop index if exists predictle_daily_pkey;

create unique index predictle_daily_pkey on public.predictle_daily using btree (date_pt);
