-- This file is autogenerated from regen-schema.ts
create table if not exists
  user_entitlements (
    auto_renew boolean default false not null,
    enabled boolean default true not null,
    entitlement_id text not null,
    expires_time timestamp with time zone,
    granted_time timestamp with time zone default now() not null,
    user_id text not null,
    constraint primary key (user_id, entitlement_id)
  );

-- Row Level Security
alter table user_entitlements enable row level security;

-- Policies
drop policy if exists "user read own" on user_entitlements;

create policy "user read own" on user_entitlements for
select
  using (firebase_uid () = user_id);

-- Indexes
drop index if exists user_entitlements_pkey;

create unique index user_entitlements_pkey on public.user_entitlements using btree (user_id, entitlement_id);
